### ISSUE TITLE
Incorrect year on some dates

### ISSUE THREAD

**Issue by samuelclay** [kurtmckee/feedparser#33] opened 2015-09-02 22:19 UTC
See the dates on this feed: https://www.daydeal.ch/rss.xml

    <pubDate>Thu, 03 Sep 15 00:01:01 +0200</pubDate>

This is being parsed as:

    >>> entry.get('published_parsed')
    time.struct_time(tm_year=200, tm_mon=9, tm_mday=2, tm_hour=15, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=245, tm_isdst=0)

In the year 200!

**Comment by louisameline** [comment] 2015-09-13 13:37
This is a duplicate of my issue : https://github.com/kurtmckee/feedparser/issues/29

**Comment by kurtmckee** [comment] 2016-02-28 22:24
This is indeed a duplicate of #29, so I'm going to close it separately. I'm currently testing @mkusiciel's patch and will be merging and closing this shortly. =)

**Closed by kurtmckee** 2016-02-28 22:24 UTC
