### ISSUE TITLE
memory leak on FeedPaser 5.2.1?

### ISSUE THREAD

**Issue by biotech7** [kurtmckee/feedparser#202] opened 2020-01-28 14:52 UTC
Recently i get to parse a RSS feed using  FeedPaser 5.2.1, accidently i find a continuous  memory increase as my  app. running without break. is there any mistake made by me?  Any help would be highly appreciated。

**my app. codes as follows(as an example):**
```
import feedparser
import time

Url = 'https://www.xxx.com/feeds/all'
myTag = ""

while(True):
    time.sleep(5)
    feed_data = feedparser.parse(Url,etag=myTag)
    myTag = feed_data.get('etag')
```
**code metioned above is compiled into .exe app throngh pyinstaller, and then let it run without break on winserver 2012.**

**Comment by kurtmckee** [comment] 2020-01-28 15:44
Thanks for notifying me about this, and for including information about the environment you're running it in!

I'll look into this, see if I can recreate it, and see if I can hunt down why you're seeing this behavior.

**Comment by biotech7** [comment] 2020-01-28 16:49
thanks for your reply.  i use python 3.7.4  x64 on anaconda env.
B.R.
Alan Lee


网易VIP邮箱提醒：安全收发邮件，务必核实往来邮件地址、银行账号等机密信息，请通过电话或视频等多种方式确认信息真实性，提高警惕，请勿轻易透露个人重要信息。
Alert message of Netease Vipmail：Never provide your password, security questions, verification codes, or any other personal important information details to anyone else.
You can identify mail message by telephone,video-chat or other ways.You should make sure that your email address, bank account and other confidential information as secure as possible. Thank you for keeping your email account secure.
On 01/28/2020 23:44, Kurt McKee wrote:
Thanks for notifying me about this, and for including information about the environment you're running it in!

I'll look into this, see if I can recreate it, and see if I can hunt down why you're seeing this behavior.

**Comment by biotech7** [comment] 2020-01-29 04:06
the same result obtained in win10 home edition

**Comment by biotech7** [comment] 2020-02-08 12:23
kurtmckee , have you confirmed it? have any test result?

**Comment by kurtmckee** [comment] 2020-02-08 14:01
Not yet.

**Comment by guyskk** [comment] 2020-03-16 16:40
@biotech7 I'm trying reproduce the problem, could you provide more details of your application and environment?

1. How long do run your application and see significant memory increase?
2. If replace url with feed content string, and remove sleep time, can you see memory increase in short time?
3. Do you use lxml, beautifulsoup or other html parsers? Could you provide the `pip freeze` output?

**Comment by biotech7** [comment] 2020-03-17 00:31
hi ，**guyskk**: just run the simple code directly(not in IDE) below, it will reproduce  the result.
```
import feedparser
import time

Url = 'https://www.dailyfxasia.com/feeds/all'
myTag = ""

while(True):
    time.sleep(5)
    feed_data = feedparser.parse(Url,etag=myTag)
    myTag = feed_data.get('etag')
```
 i use python 3.7.4  x64 on anaconda env. in win10 home edition sys. the same result obtained on winserver 2012(x64)。 if keeping running over12 hours, the memory usage will  increase step by step to more than 1.4G. 
any other running circumstance has not yet been tried。
![leak verification](https://user-images.githubusercontent.com/49674341/76810592-94588b00-6829-11ea-8198-e9ec034fc6a2.jpg)

**Comment by biotech7** [comment] 2020-03-17 00:42
it might be the consequence of unreleased memory usage of dictionary or tuple ， i tried garbage collection to release memory usage but failed。 tracing the source of memory leak was in vain。

**Comment by guyskk** [comment] 2020-03-17 06:33
@biotech7 Which python version do you use? May be it's caused by https://bugs.python.org/issue37702 , and fixed in 3.7.5: https://docs.python.org/3.7/whatsnew/changelog.html#id29

**Comment by biotech7** [comment] 2020-03-17 08:45
did you reproduce the same problem?  i use 3.7.4 (anaconda env.)

**Comment by guyskk** [comment] 2020-03-17 11:43
@biotech7  
I run your code for more than 30 minutes, can't reproduce the issue. 
You can upgrade Python to >= 3.7.5 then try again.

My test environment is Mac OS and Python 3.7.4. 

Modified code to print memory usage:

```python
import os
import time
import feedparser
import psutil


def run():
    url = 'https://www.dailyfxasia.com/feeds/all'
    my_tag = ""
    feed_data = feedparser.parse(url, etag=my_tag)
    my_tag = feed_data.get('etag')


def main():
    print('pid={}'.format(os.getpid()))
    memory_file = open('data/feed_memory.txt', 'w')
    while(True):
        for i in range(60):
            time.sleep(1)
            run()
        memory_usage = psutil.Process().memory_info().rss
        print(memory_usage)
        memory_file.write(str(memory_usage) + '\n')


if __name__ == "__main__":
    main()
```

Output (memory usage in kB):
```
pid=66140
34746368
36265984
36524032
36950016
37068800
37363712
37408768
37408768
37683200
37957632
37965824
37974016
37974016
37974016
38006784
36196352
34217984
34217984
34226176
34426880
34435072
34488320
34652160
34734080
34738176
35246080
35291136
35295232
35295232
35356672
35360768
35364864
35368960
35373056
```

Screenshot:
<img width="859" alt="屏幕快照 2020-03-17 19 37 47" src="https://user-images.githubusercontent.com/6367792/76852698-d7951700-6886-11ea-9a94-36a723ae835a.png">

**Comment by biotech7** [comment] 2020-03-17 12:35
i followed your instruction and upgraded python(including related modules/packages，but kept feedparser module intact) to V3.7.6，this bug disappeared 。Cheers！
   it may be beconcluded that the bug of memory leak is a complexity of python itself conducted drawbacks。it does't matter with feedparser module.
    i has been misleaded by this problem for quite a long time。
    many thanks for your kind help！It works!

**Comment by kurtmckee** [comment] 2020-09-01 04:52
Great news that this is resolved! @biotech7 thanks for reporting this, and @guyskk thanks for investigating!

**Closed by kurtmckee** 2020-09-01 04:52 UTC

**Comment by smithfred** [comment] 2021-02-06 16:52
After seeing this was apparently fixed, I reverted a workaround I'd put in place. Unfortunately, there's still a leak somewhere with feedparser 5.2.1, at least on Python 3.8.7.
